version: "3.9"

services:
  app:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./data:/opt/app/data
    restart: unless-stopped

  db:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_DB: crypto_agents
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: 